#include <stdint.h>
#include "ps2_keymaps.h"

uint16_t ps2_keymap_set1[128] = {
    PS2_KEY_UNKNOWN,
    PS2_KEY_ESCAPE,
    '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '=', PS2_KEY_BKSP,
    '\t','q', 'w', 'e', 't', 'y', 'u', 'i', 'o', 'p', '[', ']', '\n',
    PS2_KEY_CONTROL,
    'a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';', '\'', '`',
    PS2_KEY_SHIFT,
    '\\',
    'z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.', '/', PS2_KEY_SHIFT,
    '*',
    PS2_KEY_ALT,
    ' ',  PS2_KEY_CAPSLOCK,
    PS2_KEY_F1,
    PS2_KEY_F2,
    PS2_KEY_F3,
    PS2_KEY_F4,
    PS2_KEY_F5,
    PS2_KEY_F6,
    PS2_KEY_F7,
    PS2_KEY_F8,
    PS2_KEY_F9,
    PS2_KEY_F10,
    PS2_KEY_NUMLOCK,
    PS2_KEY_SCRLLOCK,
    '7', '8', '9',
    '-',
    '4', '5', '6',
    '+',
    '1', '2', '3',
    '0',
    '.',
    PS2_KEY_UNKNOWN,
    PS2_KEY_UNKNOWN,
    PS2_KEY_UNKNOWN,
    PS2_KEY_F11,
    PS2_KEY_F12,
    PS2_KEY_UNKNOWN,
    PS2_KEY_UNKNOWN,
    PS2_KEY_UNKNOWN,
    PS2_KEY_UNKNOWN,
};
